# -*- coding: utf-8 -*-
"""Spacy_Learn_NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10fsZbqwBlcedCk9XsPz0q3Qx9pwdEvM1
"""

!pip install spacy

!python -m spacy download en_core_web_sm

import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp("data science and ai, gen ai & agentic ai has greate carreer abead")

doc

for token in doc:
  print(token.text)

for token in doc:
  print(token.text, ':',token.pos_)

for token in doc:
  print(token.text,token.lemma_,token.pos_,token.tag_,token.dep_,token.shape_,token.is_alpha,token.is_stop)